version: '3.8'
services:
  api-singlethreaded:
    image: api-singlethreaded:latest
    build:
      context: ./api-singlethreaded
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - benchmark-network

  api-reactive:
    image: api-reactive:latest
    build:
      context: ./api-reactive
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - benchmark-network

  api-multithreading:
    image: api-multithreading:latest
    build:
      context: ./api-multithreading
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - benchmark-network

networks:
  benchmark-network:
    driver: bridge
