version: '3.9'
services:
  api-singlethreaded:
    build:
      context: ./api-singlethreaded
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 612M
        reservations:
          memory: 356M
    networks:
      - benchmark-network

  api-reactive:
    build:
      context: ./api-reactive
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 712M
        reservations:
          memory: 356M
    networks:
      - benchmark-network

  api-multithreading:
    build:
      context: ./api-multithreading
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 712M
        reservations:
          memory: 356M
    networks:
      - benchmark-network

  gatling:
    image: denvazh/gatling
    volumes:
      - ./gatling/simulations:/opt/gatling/user-files/simulations
      - ./gatling/results:/opt/gatling/results
      - ./gatling/logback.xml:/opt/gatling/conf/logback.xml
    command: [ "gatling.sh", "-s", "simulations.EmailSendingSimulation" ]
    depends_on:
      - api-singlethreaded
      - api-multithreading
      - api-reactive
    networks:
      - benchmark-network

networks:
  benchmark-network:
    driver: bridge
